<?php

/**
 * @file
 * Bitcoin Operation module hooks
 */

use Drupal\core\Form\FormStateInterface;
use Drupal\node\NodeInterface;

/**
 *
 * Implements hook to make node title hidden and not required
 *
 * @param $form
 * @param \Drupal\core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function bitcoinoperation_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  print_r($form_id);

  /* title field */
  if ($form_id === 'node_bitcoin_operation_form' || $form_id === 'node_bitcoin_operation_edit_form') {
    $form['title']['widget'][0]['value']['#value'] = t('should change after');
    $form['title']['widget'][0]['value']['#required'] = false;
    $form['title']['#type'] = 'hidden';
  }

  /* price field when create node */
  if ($form_id === 'node_bitcoin_operation_form') {
    $form['#attached']['library'][] = 'bitcoinoperation/bitcoinoperation';
  }

  /* price field when edit node */
  if ($form_id === 'node_bitcoin_operation_edit_form') {
    $form['field_price']['#disabled'] = true;
  }

}

/**
 *
 * Implements hook to change title before save the node
 *
 * @param \Drupal\node\NodeInterface $node
 */
function bitcoinoperation_node_presave(NodeInterface $node) {
  $price = $node->get('field_price')->value;
  $number = $node->get('field_number')->value;
  $node->setTitle($number . ' x (' . $price . ')');
}

